apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-producer-deployment
  # namespace: voxxed-days-2018sg
  labels:
    run: rabbitmq-producer

spec:
  replicas: 2
  selector:
    matchLabels:
      run: rabbitmq-producer

  template:
    metadata:
      labels:
        run: rabbitmq-producer
    spec:
      containers:
        - name: techtalksproducer
          image: nileshgule/techtalksproducer:rabbitmq-keda
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
            - name: RABBITMQ_HOST_NAME
              value: "rabbitmq"
            - name: RABBITMQ_USER_NAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "PASSWORD"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
