apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: techtalksapi
  # namespace: voxxed-days-2018sg
  labels:
    run: techtalksapi

spec:
  replicas: 2
  selector:
    matchLabels:
      run: techtalksapi

  template:
    metadata:
      labels:
        run: techtalksapi
    spec:
      # initContainers:
      #   - name: init-myservice
      #     image: nileshgule/sqlclient
      #     command:
      #       - "sh"
      #       - "-c"
      #       - "/opt/mssql-tools/bin/sqlcmd -S db-deployment -U sa -P January2018 -d master -i initialize-database.sql"
      containers:
      - name: techtalksapi
        image: nileshgule/techtalksapi
        env:
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:8080
          - name: ConnectionStrings__DefaultConnection
            value: "Data Source=db-deployment;Initial Catalog=TechTalksDB;User Id=SA;Password=January2018;MultipleActiveResultSets=True"
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst