apiVersion: v1

kind: Service

metadata:
  name: rabbitmq-consumer
  # namespace: voxxed-days-2018sg

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  selector:
    app: rabbitmq-consumer