apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyLw==
  # host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672/rabbitmq'
  # host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672/'